CREATE DATABASE todosdb;

CREATE TABLE task (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  completed BOOLEAN DEFAULT false,
  user_id VARCHAR(50) NOT NULL REFERENCES users(id)
);

CREATE TABLE users (
  id VARCHAR(50) PRIMARY KEY,
  fist_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50),
  email VARCHAR(150) NOT NULL UNIQUE
);
